//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>A</string>\r\n  <string>ABBR</string>\r\n  <string>ACRONYM</string>\r\n  <string" +
            ">ADDRESS</string>\r\n  <string>APPLET</string>\r\n  <string>AREA</string>\r\n  <string" +
            ">B</string>\r\n  <string>BASE</string>\r\n  <string>BASEFONT</string>\r\n  <string>BDO" +
            "</string>\r\n  <string>BGSOUND</string>\r\n  <string>BIG</string>\r\n  <string>BLINK</" +
            "string>\r\n  <string>BLOCKQUOTE</string>\r\n  <string>BODY</string>\r\n  <string>BR</s" +
            "tring>\r\n  <string>BUTTON</string>\r\n  <string>CAPTION</string>\r\n  <string>CENTER<" +
            "/string>\r\n  <string>CITE</string>\r\n  <string>CODE</string>\r\n  <string>COL</strin" +
            "g>\r\n  <string>COLGROUP</string>\r\n  <string>DD</string>\r\n  <string>DEL</string>\r\n" +
            "  <string>DFN</string>\r\n  <string>DIR</string>\r\n  <string>DIV</string>\r\n  <strin" +
            "g>DL</string>\r\n  <string>DT</string>\r\n  <string>EM</string>\r\n  <string>EMBED</st" +
            "ring>\r\n  <string>FIELDSET</string>\r\n  <string>FONT</string>\r\n  <string>FORM</str" +
            "ing>\r\n  <string>FRAME</string>\r\n  <string>FRAMESET</string>\r\n  <string>H1</strin" +
            "g>\r\n  <string>H2</string>\r\n  <string>H3</string>\r\n  <string>H4</string>\r\n  <stri" +
            "ng>H5</string>\r\n  <string>H6</string>\r\n  <string>HEAD</string>\r\n  <string>HR</st" +
            "ring>\r\n  <string>HTML</string>\r\n  <string>I</string>\r\n  <string>IFRAME</string>\r" +
            "\n  <string>ILAYER</string>\r\n  <string>IMG</string>\r\n  <string>INPUT</string>\r\n  " +
            "<string>INS</string>\r\n  <string>ISINDEX</string>\r\n  <string>KBD</string>\r\n  <str" +
            "ing>KEYGEN</string>\r\n  <string>LABEL</string>\r\n  <string>LAYER</string>\r\n  <stri" +
            "ng>LEGEND</string>\r\n  <string>LI</string>\r\n  <string>LINK</string>\r\n  <string>LI" +
            "STING</string>\r\n  <string>MAP</string>\r\n  <string>MENU</string>\r\n  <string>META<" +
            "/string>\r\n  <string>MULTICOL</string>\r\n  <string>NOBR</string>\r\n  <string>NOEMBE" +
            "D</string>\r\n  <string>NOFRAMES</string>\r\n  <string>NOLAYER</string>\r\n  <string>N" +
            "OSCRIPT</string>\r\n  <string>OBJECT</string>\r\n  <string>OL</string>\r\n  <string>OP" +
            "TGROUP</string>\r\n  <string>OPTION</string>\r\n  <string>P</string>\r\n  <string>PARA" +
            "M</string>\r\n  <string>PLAINTEXT</string>\r\n  <string>PRE</string>\r\n  <string>Q</s" +
            "tring>\r\n  <string>S</string>\r\n  <string>SAMP</string>\r\n  <string>SCRIPT</string>" +
            "\r\n  <string>SELECT</string>\r\n  <string>SERVER</string>\r\n  <string>SMALL</string>" +
            "\r\n  <string>SOUND</string>\r\n  <string>SPACER</string>\r\n  <string>SPAN</string>\r\n" +
            "  <string>STRIKE</string>\r\n  <string>STRONG</string>\r\n  <string>STYLE</string>\r\n" +
            "  <string>SUB</string>\r\n  <string>SUP</string>\r\n  <string>TABLE</string>\r\n  <str" +
            "ing>TD</string>\r\n  <string>TR</string>\r\n  <string>TBODY</string>\r\n  <string>TEXT" +
            "AREA</string>\r\n  <string>TITLE</string>\r\n  <string>TT</string>\r\n  <string>U</str" +
            "ing>\r\n  <string>UL</string>\r\n  <string>VAR</string>\r\n  <string>WBR</string>\r\n  <" +
            "string>XMP</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HtmlTags {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HtmlTags"]));
            }
            set {
                this["HtmlTags"] = value;
            }
        }
    }
}
